[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#635bff"
backgroundColor = "#f8f9fc"
secondaryBackgroundColor = "#ffffff"
textColor = "#0a2540"
font = "sans serif"

[browser]
gatherUsageStats = false
